clear all 
clc
% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/enric.guso/Documents/MATLAB/SpeechDirectivity.csv
%
% Auto-generated by MATLAB on 11-Jan-2024 10:45:22

bands = [100, 125, 160, 200, 250, 315, 400, 500, 630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000, 6300, 8000, 10000];
azel_dir = zeros(length(bands), 36, 72);
%

for k = 1:length(bands)        
    % Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 37);
    
    % Specify range and delimiter
    opts.DataLines = [73*(k-1)+2, 73*k+2];
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = ["BAND100", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Import the data
    SpeechDirectivity = readtable("/Users/enric.guso/Documents/MATLAB/SpeechDirectivity.csv", opts);
    
    directivity = table2array(SpeechDirectivity);

    directivity = directivity(1:72, 1:36);
    directivity = circshift(directivity, size(directivity,1)/4-1, 1);
    phi = linspace(0, 360, 72);
    theta = linspace(0, 180, 36);
    el = linspace(-90, 90, 36);
    az = linspace(-180, 180, 72);
    [pat_azel, az_pat, el_pat] = phitheta2azelpat(directivity', phi, theta, az, el, 'RotateZ2X',true);

    azel_dir(k,:,:) = pat_azel;
end

%% Clear temporary variables
save('azel_dir.mat', "azel_dir")
clear all
load('azel_dir.mat')
